Few docker stuff
opa

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,16 +1,11 @@
 FROM python:3.6
 
-RUN	apt-get update && apt-get install -y \
-	wget
-
-RUN wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh -O /tmp/gphoto2-updater.sh \
-&&  chmod +x /tmp/gphoto2-updater.sh \
-&&  echo 2 | /tmp/gphoto2-updater.sh
-
-
-ENV PYTHONUNBUFFERED 1
 COPY . /app
 WORKDIR /app
 
+RUN ./scripts/install_gphoto2.sh
+RUN	./scripts/install_ykush.sh ||  echo 'Ykush failed to install. Ignoring' >&2
+
+ENV PYTHONUNBUFFERED 1
 RUN pip install -r requirements.txt
 RUN python ./src/infrastructure/django_framework/manage.py migrate
